name: WebdriverIO CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install Dependencies
        run: npm install

      # ==========================================================
      # 1. RUN TESTS
      # ==========================================================
      - name: Run WebdriverIO Tests
        run: npm run run-wdio || true

      # ==========================================================
      # 2. GENERATE ALLURE REPORT ARTIFACTS
      # ==========================================================
      - name: Copy Configs and Generate Allure Report
        run: |
          npm install allure-commandline --save-dev # Ensure Allure CLI is available
          # Note: In this local 'generate-report' script handles config copying,
          # you should call it here, or run the commands directly
          cp -r allure-configs/* allure-results/ || true
          
          # Generate the report from the results
          npx allure generate allure-results --clean -o allure-report/

      # ==========================================================
      # 3. UPLOAD THE REPORT AS A DOWNLOADABLE ARTIFACT
      # ==========================================================
      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/
          retention-days: 3
